//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagerWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string EventTitle { get; set; }
    }
}
